from __future__ import annotations

from pathlib import Path
from typing import Any

from bspforge.common import file_sha256, utc_now


class RTThreadValidationGenerator:
    """Generate a small RT-Thread-native smoke test without duplicating BSP drivers."""

    def generate(self, bsp: Path, options: dict[str, Any] | None) -> dict[str, Any]:
        config = options or {}
        applications = bsp / "applications"
        applications.mkdir(parents=True, exist_ok=True)
        source = applications / "bspforge_validation.c"
        uart_name = str(config.get("uart", "uart1"))
        pin_device = str(config.get("pin_device", "pin"))
        pin_number = int(config.get("pin", -1))
        source.write_text(
            self._source(uart_name, pin_device, pin_number), encoding="utf-8"
        )
        return {
            "schema_version": "1.0",
            "created_at": utc_now(),
            "strategy": "reuse-native-device-model",
            "source": str(source),
            "source_sha256": file_sha256(source),
            "devices": [
                {"class": "serial", "name": uart_name, "operations": ["find", "open", "write"]},
                {"class": "pin", "name": pin_device, "pin": pin_number, "operations": ["mode", "write"]},
                {
                    "class": "timer",
                    "name": "rt_timer",
                    "operations": ["init", "start", "stop", "detach"],
                },
            ],
            "operation_tables": [],
            "registration_symbols": ["bspforge_validation_init", "bspforge_validation_run"],
            "required_rtthread_features": ["RT_USING_SERIAL", "RT_USING_PIN"],
            "summary": {"devices": 3, "generated_sources": 1},
        }

    @staticmethod
    def _source(uart_name: str, pin_device: str, pin_number: int) -> str:
        return f'''/* Generated by BSPForge; configuration evidence is in bspforge/. */
#include <rtdevice.h>
#include <rtthread.h>

static const char bspforge_uart_name[] = "{uart_name}";
static const char bspforge_pin_device[] = "{pin_device}";
static const rt_base_t bspforge_pin_number = {pin_number};
static struct rt_timer bspforge_timer;

static void bspforge_timer_timeout(void *parameter)
{{
    (void)parameter;
}}

int bspforge_validation_run(void)
{{
    static const char banner[] = "BSPForge RT-Thread validation\\r\\n";
    rt_device_t serial = rt_device_find(bspforge_uart_name);

    if (serial == RT_NULL)
        return -RT_ENOSYS;
    if (rt_device_open(serial, RT_DEVICE_FLAG_RDWR) != RT_EOK)
        return -RT_ERROR;
    rt_device_write(serial, 0, banner, sizeof(banner) - 1);

    if (bspforge_pin_number >= 0)
    {{
        (void)bspforge_pin_device;
        rt_pin_mode(bspforge_pin_number, PIN_MODE_OUTPUT);
        rt_pin_write(bspforge_pin_number, PIN_HIGH);
    }}

    rt_timer_init(&bspforge_timer, "bfval", bspforge_timer_timeout, RT_NULL,
                  1, RT_TIMER_FLAG_ONE_SHOT | RT_TIMER_FLAG_HARD_TIMER);
    rt_timer_start(&bspforge_timer);
    rt_timer_stop(&bspforge_timer);
    rt_timer_detach(&bspforge_timer);
    return RT_EOK;
}}

int bspforge_validation_init(void)
{{
    return bspforge_validation_run();
}}
INIT_APP_EXPORT(bspforge_validation_init);

#ifdef RT_USING_FINSH
#include <finsh.h>
MSH_CMD_EXPORT(bspforge_validation_run, run BSPForge native-device validation);
#endif
'''
