from __future__ import annotations

from pathlib import Path
from typing import Any

from bspforge.common import file_sha256, utc_now


class ZephyrValidationGenerator:
    """Generate the common board protocol over Zephyr and functional bindings."""

    def generate(
        self,
        source_dir: Path,
        board: str,
        build_id: str,
        functional: bool,
        native_devices: bool = False,
        standard_devices: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if standard_devices:
            header = source_dir / "bspforge_zephyr_devices.h"
            header.write_text(
                self._standard_device_header(standard_devices), encoding="utf-8"
            )
        source = source_dir / "main.c"
        source.write_text(
            self._source(
                board,
                build_id,
                functional,
                native_devices or bool(standard_devices),
                standard_devices=bool(standard_devices),
            ),
            encoding="utf-8",
        )
        return {
            "schema_version": "1.0",
            "created_at": utc_now(),
            "strategy": (
                "zephyr-standard-devicetree-device-selftest"
                if standard_devices
                else "zephyr-native-sdk-device-selftest"
                if native_devices
                else (
                    "sdk-functional-binding-selftest"
                    if functional
                    else "zephyr-native-smoke-selftest"
                )
            ),
            "protocol_version": "1.0",
            "source": str(source),
            "source_sha256": file_sha256(source),
            "registration_symbols": [
                "bspforge_zephyr_validation_init",
                "bspforge_zephyr_validation_run",
            ],
        }

    @staticmethod
    def _source(
        board: str,
        build_id: str,
        functional: bool,
        native_devices: bool = False,
        standard_devices: bool = False,
    ) -> str:
        if standard_devices:
            binding_include = '#include "bspforge_zephyr_devices.h"\n'
            functional_helpers = ZephyrValidationGenerator._native_device_helpers()
            command_body = ZephyrValidationGenerator._standard_device_commands()
        elif native_devices:
            binding_include = '#include "bspforge_zephyr_devices.h"\n'
            functional_helpers = ZephyrValidationGenerator._native_device_helpers()
            command_body = ZephyrValidationGenerator._native_device_commands()
        elif functional:
            binding_include = '#include "bspforge_bindings.h"\n'
            functional_helpers = ZephyrValidationGenerator._functional_helpers()
            command_body = ZephyrValidationGenerator._functional_commands()
        else:
            binding_include = ""
            functional_helpers = ""
            command_body = ZephyrValidationGenerator._smoke_commands()
        source = r'''/* Generated by BSPForge; evidence is stored in bspforge/. */
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/clock_control.h>
#include <zephyr/drivers/counter.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/uart.h>
#include <zephyr/init.h>
#include <zephyr/kernel.h>
#include <errno.h>
#include <string.h>
@BINDING_INCLUDE@
#define BSPFORGE_LED_NODE DT_ALIAS(led0)

@FUNCTIONAL_HELPERS@
int bspforge_zephyr_validation_run(void)
{
    static const char banner[] =
        "{\"bspforge\":true,\"protocol\":\"1.0\","
        "\"event\":\"boot\",\"rtos\":\"zephyr\","
        "\"board\":\"@BOARD@\",\"build_id\":\"@BUILD_ID@\","
        "\"stage\":\"application\"}\r\n";
    const struct device *console = DEVICE_DT_GET(DT_CHOSEN(zephyr_console));

    if (!device_is_ready(console))
        return -ENODEV;
    for (size_t index = 0; index < sizeof(banner) - 1; ++index)
        uart_poll_out(console, banner[index]);
    return 0;
}

static void bspforge_result(const char *request_id, const char *command,
                            const char *status, const char *metrics)
{
    printk("{\"bspforge\":true,\"protocol\":\"1.0\","
           "\"event\":\"result\",\"request_id\":\"%s\","
           "\"command\":\"%s\",\"status\":\"%s\","
           "\"metrics\":%s}\r\n",
           request_id, command, status, metrics);
}

static void bspforge_selftest(const char *request_id, const char *command)
{
@COMMAND_BODY@
}

int bspforge_zephyr_validation_init(void)
{
    return 0;
}
SYS_INIT(bspforge_zephyr_validation_init, APPLICATION, 90);

int main(void)
{
    const struct device *console = DEVICE_DT_GET(DT_CHOSEN(zephyr_console));
    char line[96];
    size_t length = 0;

    if (bspforge_zephyr_validation_run() != 0)
        return -ENODEV;
    while (device_is_ready(console)) {
        unsigned char value;
        if (uart_poll_in(console, &value) != 0) {
            k_busy_wait(50);
            continue;
        }
        if (value == '\r' || value == '\n') {
            char *request_id;
            char *command;
            char *separator;
            static const char prefix[] = "bspforge_selftest ";
            if (length == 0)
                continue;
            line[length] = '\0';
            request_id = line + sizeof(prefix) - 1;
            separator = strchr(request_id, ' ');
            if (strncmp(line, prefix, sizeof(prefix) - 1) == 0 && separator) {
                *separator = '\0';
                command = separator + 1;
                bspforge_selftest(request_id, command);
            }
            length = 0;
        } else if (length + 1 < sizeof(line)) {
            line[length++] = (char)value;
        } else {
            length = 0;
        }
    }
    return -ENODEV;
}
'''
        return (
            source.replace("@BOARD@", board)
            .replace("@BUILD_ID@", build_id)
            .replace("@BINDING_INCLUDE@", binding_include.rstrip())
            .replace("@FUNCTIONAL_HELPERS@", functional_helpers.rstrip())
            .replace("@COMMAND_BODY@", command_body.rstrip())
        )

    @staticmethod
    def _native_device_helpers() -> str:
        return r'''
static volatile uint32_t bspforge_gpio_irq_fires;
static volatile uint32_t bspforge_timer_fires;
static struct gpio_callback bspforge_gpio_callback_data;

static void bspforge_native_gpio_callback(const struct device *device,
                                          struct gpio_callback *callback,
                                          gpio_port_pins_t pins)
{
    ARG_UNUSED(device);
    ARG_UNUSED(callback);
    ARG_UNUSED(pins);
    bspforge_gpio_irq_fires++;
}

static void bspforge_native_alarm_callback(const struct device *device,
                                            uint8_t channel,
                                            uint32_t ticks,
                                            void *user_data)
{
    ARG_UNUSED(device);
    ARG_UNUSED(channel);
    ARG_UNUSED(ticks);
    ARG_UNUSED(user_data);
    bspforge_timer_fires++;
}

static int bspforge_native_wait_counter(volatile uint32_t *counter,
                                        uint32_t expected,
                                        uint32_t timeout_ms,
                                        uint32_t *elapsed_ms)
{
    int64_t started = k_uptime_get();

    while (*counter < expected &&
           (uint32_t)(k_uptime_get() - started) < timeout_ms)
        k_msleep(1);
    *elapsed_ms = (uint32_t)(k_uptime_get() - started);
    return *counter >= expected ? 0 : -ETIMEDOUT;
}

static int bspforge_native_timer_test(bool periodic, uint32_t expected,
                                      uint32_t *fires,
                                      uint32_t *elapsed_ms)
{
    const struct device *counter = bspforge_zephyr_counter_device();
    int result;

    if (!device_is_ready(counter))
        return -ENODEV;
    (void)counter_stop(counter);
    bspforge_timer_fires = 0U;
    if (periodic) {
        const struct counter_alarm_cfg alarm = {
            .ticks = 10000000U,
            .callback = bspforge_native_alarm_callback,
            .user_data = NULL,
            .flags = 0U,
        };
        uint32_t total_elapsed = 0U;

        result = counter_start(counter);
        for (uint32_t target = 1U; result == 0 && target <= expected; ++target) {
            uint32_t step_elapsed = 0U;

            result = counter_set_channel_alarm(counter, 0U, &alarm);
            if (result == 0)
                result = bspforge_native_wait_counter(&bspforge_timer_fires,
                                                       target, 500U,
                                                       &step_elapsed);
            total_elapsed += step_elapsed;
        }
        *elapsed_ms = total_elapsed;
    } else {
        const struct counter_alarm_cfg alarm = {
            .ticks = 10000000U,
            .callback = bspforge_native_alarm_callback,
            .user_data = NULL,
            .flags = 0U,
        };
        result = counter_start(counter);
        if (result == 0)
            result = counter_set_channel_alarm(counter, 0U, &alarm);
    }
    if (result == 0 && !periodic)
        result = bspforge_native_wait_counter(&bspforge_timer_fires, expected,
                                              1000U, elapsed_ms);
    (void)counter_stop(counter);
    *fires = bspforge_timer_fires;
    if (result == 0 && *fires != expected)
        result = -EIO;
    return result;
}
'''

    @staticmethod
    def _native_device_commands() -> str:
        return r'''    char metrics[192];

    if (strcmp(command, "info") == 0 || strcmp(command, "stability") == 0) {
        const struct device *clock = bspforge_zephyr_clock_device();
        const struct device *uart = bspforge_zephyr_uart_device();
        const struct device *gpio = bspforge_zephyr_gpio_device();
        const struct device *gpio_input = bspforge_zephyr_gpio_input_device();
        const struct device *counter = bspforge_zephyr_counter_device();
        bool ready = device_is_ready(clock) && device_is_ready(uart) &&
                     device_is_ready(gpio) && device_is_ready(gpio_input) &&
                     device_is_ready(counter);

        bspforge_result(request_id, command, ready ? "pass" : "fail",
                        "{\"native_devices\":4}");
        return;
    }
    if (strcmp(command, "clock.basic") == 0) {
        const struct device *clock = bspforge_zephyr_clock_device();
        clock_control_subsys_t cpu =
            (clock_control_subsys_t)(uintptr_t)BSPFORGE_ZEPHYR_CLOCK_CPU;
        clock_control_subsys_t timer =
            (clock_control_subsys_t)(uintptr_t)BSPFORGE_ZEPHYR_CLOCK_TIMER;
        uint32_t cpu_hz = 0U;
        uint32_t timer_hz = 0U;
        int result = device_is_ready(clock) ? 0 : -ENODEV;

        if (result == 0)
            result = clock_control_get_rate(clock, cpu, &cpu_hz);
        if (result == 0)
            result = clock_control_on(clock, timer);
        if (result == 0)
            result = clock_control_get_rate(clock, timer, &timer_hz);
        if (device_is_ready(clock) && clock_control_off(clock, timer) != 0)
            result = -EIO;
        snprintk(metrics, sizeof(metrics),
                 "{\"cpu_hz\":%u,\"timer_hz\":%u}", cpu_hz, timer_hz);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail",
                        metrics);
        return;
    }
    if (strcmp(command, "uart.loopback") == 0) {
        const struct device *uart = bspforge_zephyr_uart_device();
        uint32_t bytes = 0U;
        uint32_t errors = 0U;
        int result = device_is_ready(uart) ? 0 : -ENODEV;

        for (uint32_t index = 0U; result == 0 && index < 16U; ++index) {
            uint8_t sent = (uint8_t)(0x31U + index * 7U);
            unsigned char received = 0U;
            int64_t deadline;
            int count = -1;

            if (uart_fifo_fill(uart, &sent, 1) != 1) {
                errors++;
                continue;
            }
            deadline = k_uptime_get() + 100;
            do {
                count = uart_fifo_read(uart, &received, 1);
                if (count == 1)
                    break;
                k_busy_wait(50);
            } while (k_uptime_get() < deadline);
            if (count != 1) {
                errors++;
                continue;
            }
            bytes++;
            if (received != sent)
                errors++;
        }
        if (bytes != 16U || errors != 0U)
            result = -EIO;
        snprintk(metrics, sizeof(metrics),
                 "{\"bytes\":%u,\"errors\":%u}", bytes, errors);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail",
                        metrics);
        return;
    }
    if (strcmp(command, "gpio.toggle") == 0) {
        const struct device *gpio = bspforge_zephyr_gpio_device();
        const struct device *gpio_input = bspforge_zephyr_gpio_input_device();
        int low_latch = -1;
        int high_latch = -1;
        int input_low = -1;
        int input_high = -1;
        int result = device_is_ready(gpio) && device_is_ready(gpio_input)
                         ? 0 : -ENODEV;

        if (result == 0)
            result = gpio_pin_configure(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN,
                                        GPIO_OUTPUT_INACTIVE);
        if (result == 0)
            result = gpio_pin_configure(gpio_input, BSPFORGE_ZEPHYR_GPIO_INPUT_PIN,
                                        GPIO_INPUT | GPIO_PULL_DOWN);
        if (result == 0)
            result = gpio_pin_set(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN, 0);
        k_msleep(2);
        if (result == 0) {
            low_latch = gpio_pin_get(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN);
            input_low = gpio_pin_get(gpio_input, BSPFORGE_ZEPHYR_GPIO_INPUT_PIN);
            result = gpio_pin_set(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN, 1);
        }
        k_msleep(2);
        if (result == 0) {
            high_latch = gpio_pin_get(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN);
            input_high = gpio_pin_get(gpio_input, BSPFORGE_ZEPHYR_GPIO_INPUT_PIN);
        }
        if (low_latch != 0 || high_latch != 1 || input_low != 0 || input_high != 1)
            result = -EIO;
        snprintk(metrics, sizeof(metrics),
                 "{\"output_low_latch\":%d,\"output_high_latch\":%d,"
                 "\"input_low\":%d,\"input_high\":%d}",
                 low_latch, high_latch, input_low, input_high);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail",
                        metrics);
        return;
    }
    if (strcmp(command, "gpio.irq") == 0) {
        const struct device *gpio = bspforge_zephyr_gpio_device();
        const struct device *gpio_input = bspforge_zephyr_gpio_input_device();
        uint32_t elapsed_ms = 0U;
        int result = device_is_ready(gpio) && device_is_ready(gpio_input)
                         ? 0 : -ENODEV;

        if (result == 0)
            result = gpio_pin_configure(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN,
                                        GPIO_OUTPUT_INACTIVE);
        if (result == 0)
            result = gpio_pin_configure(gpio_input, BSPFORGE_ZEPHYR_GPIO_INPUT_PIN,
                                        GPIO_INPUT | GPIO_PULL_DOWN);
        if (result == 0)
            result = gpio_pin_set(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN, 0);
        k_msleep(2);
        bspforge_gpio_irq_fires = 0U;
        gpio_init_callback(&bspforge_gpio_callback_data,
                           bspforge_native_gpio_callback,
                           BIT(BSPFORGE_ZEPHYR_GPIO_INPUT_PIN));
        if (result == 0)
            result = gpio_add_callback(gpio_input, &bspforge_gpio_callback_data);
        if (result == 0)
            result = gpio_pin_interrupt_configure(
                gpio_input, BSPFORGE_ZEPHYR_GPIO_INPUT_PIN, GPIO_INT_EDGE_RISING);
        if (result == 0)
            result = gpio_pin_set(gpio, BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN, 1);
        if (result == 0)
            result = bspforge_native_wait_counter(&bspforge_gpio_irq_fires,
                                                  1U, 500U, &elapsed_ms);
        (void)gpio_pin_interrupt_configure(
            gpio_input, BSPFORGE_ZEPHYR_GPIO_INPUT_PIN, GPIO_INT_DISABLE);
        (void)gpio_remove_callback(gpio_input, &bspforge_gpio_callback_data);
        snprintk(metrics, sizeof(metrics),
                 "{\"irq_callbacks\":%u,\"elapsed_ms\":%u}",
                 bspforge_gpio_irq_fires, elapsed_ms);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail",
                        metrics);
        return;
    }
    if (strcmp(command, "interrupt.basic") == 0 ||
        strcmp(command, "timer.oneshot") == 0 ||
        strcmp(command, "timer.periodic") == 0) {
        bool periodic = strcmp(command, "timer.periodic") == 0;
        uint32_t expected = periodic ? 3U : 1U;
        uint32_t fires = 0U;
        uint32_t elapsed_ms = 0U;
        int result = bspforge_native_timer_test(periodic, expected,
                                                &fires, &elapsed_ms);

        snprintk(metrics, sizeof(metrics),
                 "{\"callbacks\":%u,\"elapsed_ms\":%u}", fires, elapsed_ms);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail",
                        metrics);
        return;
    }
    bspforge_result(request_id, command, "fail", "{}");
'''

    @staticmethod
    def _standard_device_header(options: dict[str, Any]) -> str:
        required = {
            "uart_node", "gpio_output_node", "gpio_input_node", "counter_node",
            "gpio_output_pin", "gpio_input_pin",
        }
        missing = sorted(required - options.keys())
        if missing:
            raise ValueError("standard device validation lacks: " + ", ".join(missing))
        nodes = {
            key: str(options[key])
            for key in ("uart_node", "gpio_output_node", "gpio_input_node", "counter_node")
        }
        if any(not value.replace("_", "").isalnum() for value in nodes.values()):
            raise ValueError("Zephyr node labels must be alphanumeric identifiers")
        return f'''/* Generated by BSPForge. Do not edit manually. */
#ifndef BSPFORGE_ZEPHYR_DEVICES_H
#define BSPFORGE_ZEPHYR_DEVICES_H

#include <zephyr/device.h>
#include <zephyr/devicetree.h>

#define BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN {int(options["gpio_output_pin"])}U
#define BSPFORGE_ZEPHYR_GPIO_INPUT_PIN {int(options["gpio_input_pin"])}U

static inline const struct device *bspforge_zephyr_uart_device(void)
{{ return DEVICE_DT_GET(DT_NODELABEL({nodes["uart_node"]})); }}
static inline const struct device *bspforge_zephyr_gpio_device(void)
{{ return DEVICE_DT_GET(DT_NODELABEL({nodes["gpio_output_node"]})); }}
static inline const struct device *bspforge_zephyr_gpio_input_device(void)
{{ return DEVICE_DT_GET(DT_NODELABEL({nodes["gpio_input_node"]})); }}
static inline const struct device *bspforge_zephyr_counter_device(void)
{{ return DEVICE_DT_GET(DT_NODELABEL({nodes["counter_node"]})); }}

#endif
'''

    @staticmethod
    def _standard_device_commands() -> str:
        body = ZephyrValidationGenerator._native_device_commands()
        old_info = '''        const struct device *clock = bspforge_zephyr_clock_device();
        const struct device *uart = bspforge_zephyr_uart_device();
        const struct device *gpio = bspforge_zephyr_gpio_device();
        const struct device *gpio_input = bspforge_zephyr_gpio_input_device();
        const struct device *counter = bspforge_zephyr_counter_device();
        bool ready = device_is_ready(clock) && device_is_ready(uart) &&
                     device_is_ready(gpio) && device_is_ready(gpio_input) &&
                     device_is_ready(counter);

        bspforge_result(request_id, command, ready ? "pass" : "fail",
                        "{\\"native_devices\\":4}");'''
        new_info = '''        const struct device *uart = bspforge_zephyr_uart_device();
        const struct device *gpio = bspforge_zephyr_gpio_device();
        const struct device *gpio_input = bspforge_zephyr_gpio_input_device();
        const struct device *counter = bspforge_zephyr_counter_device();
        bool ready = device_is_ready(uart) && device_is_ready(gpio) &&
                     device_is_ready(gpio_input) && device_is_ready(counter);

        bspforge_result(request_id, command, ready ? "pass" : "fail",
                        "{\\"native_devices\\":4}");'''
        old_clock = '''        const struct device *clock = bspforge_zephyr_clock_device();
        clock_control_subsys_t cpu =
            (clock_control_subsys_t)(uintptr_t)BSPFORGE_ZEPHYR_CLOCK_CPU;
        clock_control_subsys_t timer =
            (clock_control_subsys_t)(uintptr_t)BSPFORGE_ZEPHYR_CLOCK_TIMER;
        uint32_t cpu_hz = 0U;
        uint32_t timer_hz = 0U;
        int result = device_is_ready(clock) ? 0 : -ENODEV;

        if (result == 0)
            result = clock_control_get_rate(clock, cpu, &cpu_hz);
        if (result == 0)
            result = clock_control_on(clock, timer);
        if (result == 0)
            result = clock_control_get_rate(clock, timer, &timer_hz);
        if (device_is_ready(clock) && clock_control_off(clock, timer) != 0)
            result = -EIO;'''
        new_clock = '''        const struct device *counter = bspforge_zephyr_counter_device();
        uint32_t cpu_hz = sys_clock_hw_cycles_per_sec();
        uint32_t timer_hz = device_is_ready(counter)
                                ? counter_get_frequency(counter) : 0U;
        int result = cpu_hz > 0U && timer_hz > 0U ? 0 : -ENODEV;'''
        if old_info not in body or old_clock not in body:
            raise RuntimeError("Zephyr native validation template changed unexpectedly")
        return body.replace(old_info, new_info, 1).replace(old_clock, new_clock, 1)

    @staticmethod
    def _functional_helpers() -> str:
        return r'''
static volatile uint32_t bspforge_gpio_irq_fires;
static volatile uint32_t bspforge_timer_fires;
static volatile uint32_t bspforge_timer_target;

static int bspforge_gpio_callback(void *context)
{
    ARG_UNUSED(context);
    bspforge_gpio_irq_fires++;
    return 0;
}

static int bspforge_timer_callback(void *context)
{
    ARG_UNUSED(context);
    bspforge_timer_fires++;
    if (bspforge_timer_fires >= bspforge_timer_target)
        bspforge_timer_quiesce();
    return 0;
}

static int bspforge_wait_counter(volatile uint32_t *counter, uint32_t expected,
                                 uint32_t timeout_ms, uint32_t *elapsed_ms)
{
    int64_t started = k_uptime_get();

    while (*counter < expected &&
           (uint32_t)(k_uptime_get() - started) < timeout_ms)
        k_msleep(1);
    *elapsed_ms = (uint32_t)(k_uptime_get() - started);
    return *counter >= expected ? 0 : -ETIMEDOUT;
}

static int bspforge_hardware_timer_test(bool periodic, uint32_t expected,
                                        uint32_t *fires, uint32_t *elapsed_ms)
{
    int result;

    bspforge_timer_fires = 0U;
    bspforge_timer_target = expected;
    result = bspforge_timer_initialize();
    if (result == 0)
        result = bspforge_timer_start(10000000ULL, !periodic,
                                      bspforge_timer_callback, NULL);
    if (result == 0)
        result = bspforge_wait_counter(&bspforge_timer_fires, expected,
                                       1000U, elapsed_ms);
    (void)bspforge_timer_stop();
    *fires = bspforge_timer_fires;
    if (result == 0 && *fires != expected)
        result = -EIO;
    return result;
}
'''

    @staticmethod
    def _functional_commands() -> str:
        return r'''    char metrics[192];
    const char *status = "fail";

    if (strcmp(command, "info") == 0 || strcmp(command, "stability") == 0) {
        bspforge_result(request_id, command, "pass", "{}");
        return;
    }
    if (strcmp(command, "clock.basic") == 0) {
        uint32_t cpu_hz = 0U;
        uint32_t timer_hz = 0U;
        int result = bspforge_clock_test(&cpu_hz, &timer_hz);
        snprintk(metrics, sizeof(metrics),
                 "{\"cpu_hz\":%u,\"timer_hz\":%u}", cpu_hz, timer_hz);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail", metrics);
        return;
    }
    if (strcmp(command, "uart.loopback") == 0) {
        uint32_t bytes = 0U;
        uint32_t errors = 0U;
        int result = bspforge_uart_initialize();
        for (uint32_t index = 0U; result == 0 && index < 16U; ++index) {
            uint8_t sent = (uint8_t)(0x31U + index * 7U);
            uint8_t received = 0U;
            int64_t deadline;
            int count = bspforge_uart_write(&sent, 1U);

            if (count != 1) {
                errors++;
                continue;
            }
            deadline = k_uptime_get() + 100;
            do {
                count = bspforge_uart_read(&received, 1U);
                if (count == 1)
                    break;
                k_busy_wait(50);
            } while (k_uptime_get() < deadline);
            if (count != 1) {
                errors++;
                continue;
            }
            bytes++;
            if (received != sent)
                errors++;
        }
        if (bytes != 16U || errors != 0U)
            result = -EIO;
        snprintk(metrics, sizeof(metrics),
                 "{\"bytes\":%u,\"errors\":%u}", bytes, errors);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail", metrics);
        return;
    }
    if (strcmp(command, "gpio.toggle") == 0) {
        int low_latch = -1;
        int high_latch = -1;
        int input_low = -1;
        int input_high = -1;
        int result = bspforge_gpio_initialize();

        if (result == 0)
            result = bspforge_gpio_write(0U);
        k_msleep(2);
        if (result == 0) {
            low_latch = bspforge_gpio_output_latch();
            input_low = bspforge_gpio_read();
            result = bspforge_gpio_write(1U);
        }
        k_msleep(2);
        if (result == 0) {
            high_latch = bspforge_gpio_output_latch();
            input_high = bspforge_gpio_read();
        }
        if (low_latch != 0 || high_latch != 1 || input_low != 0 || input_high != 1)
            result = -EIO;
        snprintk(metrics, sizeof(metrics),
                 "{\"output_low_latch\":%d,\"output_high_latch\":%d,"
                 "\"input_low\":%d,\"input_high\":%d}",
                 low_latch, high_latch, input_low, input_high);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail", metrics);
        return;
    }
    if (strcmp(command, "gpio.irq") == 0) {
        uint32_t elapsed_ms = 0U;
        int result = bspforge_gpio_initialize();

        if (result == 0)
            result = bspforge_gpio_write(0U);
        k_msleep(2);
        bspforge_gpio_irq_fires = 0U;
        if (result == 0)
            result = bspforge_gpio_irq_register(bspforge_gpio_callback, NULL);
        if (result == 0)
            result = bspforge_gpio_write(1U);
        if (result == 0)
            result = bspforge_wait_counter(&bspforge_gpio_irq_fires, 1U,
                                           500U, &elapsed_ms);
        bspforge_gpio_irq_unregister();
        snprintk(metrics, sizeof(metrics),
                 "{\"irq_callbacks\":%u,\"elapsed_ms\":%u}",
                 bspforge_gpio_irq_fires, elapsed_ms);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail", metrics);
        return;
    }
    if (strcmp(command, "interrupt.basic") == 0 ||
        strcmp(command, "timer.oneshot") == 0 ||
        strcmp(command, "timer.periodic") == 0) {
        bool periodic = strcmp(command, "timer.periodic") == 0;
        uint32_t expected = periodic ? 3U : 1U;
        uint32_t fires = 0U;
        uint32_t elapsed_ms = 0U;
        int result = bspforge_hardware_timer_test(periodic, expected,
                                                   &fires, &elapsed_ms);
        snprintk(metrics, sizeof(metrics),
                 "{\"callbacks\":%u,\"elapsed_ms\":%u}", fires, elapsed_ms);
        bspforge_result(request_id, command, result == 0 ? "pass" : "fail", metrics);
        return;
    }
    bspforge_result(request_id, command, status, "{}");
'''

    @staticmethod
    def _smoke_commands() -> str:
        return r'''    const char *status = "unsupported";
    uint32_t elapsed = 0U;
    char metrics[64];

    if (strcmp(command, "info") == 0 || strcmp(command, "stability") == 0)
        status = "pass";
    else if (strcmp(command, "gpio.toggle") == 0) {
#if DT_NODE_HAS_STATUS(BSPFORGE_LED_NODE, okay)
        const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(BSPFORGE_LED_NODE, gpios);
        if (gpio_is_ready_dt(&led) &&
            gpio_pin_configure_dt(&led, GPIO_OUTPUT_INACTIVE) == 0 &&
            gpio_pin_toggle_dt(&led) == 0 && gpio_pin_toggle_dt(&led) == 0)
            status = "pass";
        else
            status = "fail";
#endif
    } else if (strcmp(command, "timer.oneshot") == 0 ||
               strcmp(command, "timer.periodic") == 0) {
        int64_t started = k_uptime_get();
        k_sleep(K_MSEC(2));
        elapsed = (uint32_t)(k_uptime_get() - started);
        status = "pass";
    }
    snprintk(metrics, sizeof(metrics), "{\"elapsed_ms\":%u}", elapsed);
    bspforge_result(request_id, command, status, metrics);
'''
