from __future__ import annotations

from pathlib import Path
from typing import Any

from bspforge.common import file_sha256, utc_now


class ZephyrDeviceModelGenerator:
    """Generate Zephyr-native devices backed by the generated SDK adapter."""

    def generate(
        self,
        source_dir: Path,
        options: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        validation = (options or {}).get("validation", {})
        output_pin = int(validation.get("gpio_binding_pin", 29))
        input_pin = int(validation.get("gpio_input_binding_pin", 28))
        if not all(0 <= item <= 31 for item in (output_pin, input_pin)):
            raise ValueError("K210 GPIOHS pin must be in [0, 31]")
        if output_pin == input_pin:
            raise ValueError("Zephyr GPIO input and output pins must be different")

        header = source_dir / "bspforge_zephyr_devices.h"
        source = source_dir / "bspforge_zephyr_devices.c"
        header.write_text(self._header(output_pin, input_pin), encoding="utf-8")
        source.write_text(self._source(output_pin, input_pin), encoding="utf-8")
        registration_symbols = [
            "bspforge_zephyr_clock_device",
            "bspforge_zephyr_counter_device",
            "bspforge_zephyr_gpio_device",
            "bspforge_zephyr_gpio_input_device",
            "bspforge_zephyr_uart_device",
        ]
        return {
            "schema_version": "1.0",
            "created_at": utc_now(),
            "backend": "zephyr",
            "strategy": "zephyr-native-sdk-backed-device-model",
            "source": str(source),
            "header": str(header),
            "source_sha256": file_sha256(source),
            "header_sha256": file_sha256(header),
            "sources": [str(source)],
            "devices": [
                {
                    "class": "clock_control",
                    "name": "bspforge_clock",
                    "operations": ["on", "off", "get_rate", "get_status"],
                },
                {
                    "class": "serial",
                    "name": "bspforge_uart",
                    "operations": ["configure", "config_get", "poll_out", "poll_in"],
                },
                {
                    "class": "gpio",
                    "name": "bspforge_gpio",
                    "pins": {"output": output_pin, "input": input_pin},
                    "operations": [
                        "pin_configure",
                        "port_get_raw",
                        "port_set_masked_raw",
                        "port_set_bits_raw",
                        "port_clear_bits_raw",
                        "port_toggle_bits",
                        "pin_interrupt_configure",
                        "manage_callback",
                    ],
                },
                {
                    "class": "counter",
                    "name": "bspforge_counter",
                    "operations": [
                        "start",
                        "stop",
                        "get_value",
                        "set_alarm",
                        "cancel_alarm",
                        "set_top_value",
                    ],
                },
            ],
            "subsystems": [
                {
                    "class": "interrupt_controller",
                    "implementation": "Zephyr second-level IRQ table and K210 PLIC bridge",
                    "operations": ["connect", "enable", "disable", "dispatch"],
                }
            ],
            "operation_tables": [
                "bspforge_clock_api",
                "bspforge_uart_api",
                "bspforge_gpio_api",
                "bspforge_counter_api",
            ],
            "registration_symbols": registration_symbols,
            "required_zephyr_features": [
                "CONFIG_CLOCK_CONTROL",
                "CONFIG_COUNTER",
                "CONFIG_GPIO",
                "CONFIG_SERIAL",
                "CONFIG_UART_USE_RUNTIME_CONFIGURE",
            ],
            "summary": {
                "devices": 4,
                "operation_tables": 4,
                "registration_functions": len(registration_symbols),
                "interrupt_subsystems": 1,
            },
        }

    @staticmethod
    def _header(output_pin: int, input_pin: int) -> str:
        return f'''/* Generated by BSPForge. Do not edit manually. */
#ifndef BSPFORGE_ZEPHYR_DEVICES_H
#define BSPFORGE_ZEPHYR_DEVICES_H

#include <zephyr/device.h>

#define BSPFORGE_ZEPHYR_GPIO_OUTPUT_PIN {output_pin}U
#define BSPFORGE_ZEPHYR_GPIO_INPUT_PIN {input_pin}U

enum bspforge_zephyr_clock_subsystem {{
    BSPFORGE_ZEPHYR_CLOCK_CPU = 0,
    BSPFORGE_ZEPHYR_CLOCK_TIMER = 1,
}};

const struct device *bspforge_zephyr_clock_device(void);
const struct device *bspforge_zephyr_uart_device(void);
const struct device *bspforge_zephyr_gpio_device(void);
const struct device *bspforge_zephyr_gpio_input_device(void);
const struct device *bspforge_zephyr_counter_device(void);

#endif
'''

    @staticmethod
    def _source(output_pin: int, input_pin: int) -> str:
        return f'''/* Generated Zephyr device model backed by K210 SDK bindings. */
#include "bspforge_bindings.h"
#include "bspforge_zephyr_devices.h"

#include <zephyr/device.h>
#include <zephyr/drivers/clock_control.h>
#include <zephyr/drivers/counter.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/gpio/gpio_utils.h>
#include <zephyr/drivers/uart.h>
#include <zephyr/kernel.h>
#include <zephyr/sys/util.h>
#include <errno.h>
#include <stdint.h>
#include <string.h>

#define BSPFORGE_CLOCK_NAME "bspforge_clock"
#define BSPFORGE_UART_NAME "bspforge_uart"
#define BSPFORGE_GPIO_NAME "bspforge_gpio"
#define BSPFORGE_COUNTER_NAME "bspforge_counter"
#define BSPFORGE_GPIO_OUTPUT_PIN {output_pin}U
#define BSPFORGE_GPIO_INPUT_PIN {input_pin}U

struct bspforge_clock_data {{
    bool cpu_on;
    bool timer_on;
}};

static int bspforge_clock_on_api(const struct device *dev,
                                 clock_control_subsys_t subsystem)
{{
    struct bspforge_clock_data *data = dev->data;
    uint32_t id = (uint32_t)(uintptr_t)subsystem;
    int result = bspforge_clock_on(id);

    if (result == 0) {{
        if (id == BSPFORGE_ZEPHYR_CLOCK_CPU)
            data->cpu_on = true;
        else if (id == BSPFORGE_ZEPHYR_CLOCK_TIMER)
            data->timer_on = true;
    }}
    return result;
}}

static int bspforge_clock_off_api(const struct device *dev,
                                  clock_control_subsys_t subsystem)
{{
    struct bspforge_clock_data *data = dev->data;
    uint32_t id = (uint32_t)(uintptr_t)subsystem;
    int result = bspforge_clock_off(id);

    if (result == 0 && id == BSPFORGE_ZEPHYR_CLOCK_TIMER)
        data->timer_on = false;
    return result;
}}

static int bspforge_clock_get_rate_api(const struct device *dev,
                                       clock_control_subsys_t subsystem,
                                       uint32_t *rate)
{{
    ARG_UNUSED(dev);
    return bspforge_clock_get_rate((uint32_t)(uintptr_t)subsystem, rate);
}}

static enum clock_control_status bspforge_clock_status_api(
    const struct device *dev, clock_control_subsys_t subsystem)
{{
    const struct bspforge_clock_data *data = dev->data;
    uint32_t id = (uint32_t)(uintptr_t)subsystem;

    if (id == BSPFORGE_ZEPHYR_CLOCK_CPU)
        return data->cpu_on ? CLOCK_CONTROL_STATUS_ON : CLOCK_CONTROL_STATUS_OFF;
    if (id == BSPFORGE_ZEPHYR_CLOCK_TIMER)
        return data->timer_on ? CLOCK_CONTROL_STATUS_ON : CLOCK_CONTROL_STATUS_OFF;
    return CLOCK_CONTROL_STATUS_UNKNOWN;
}}

static DEVICE_API(clock_control, bspforge_clock_api) = {{
    .on = bspforge_clock_on_api,
    .off = bspforge_clock_off_api,
    .get_rate = bspforge_clock_get_rate_api,
    .get_status = bspforge_clock_status_api,
}};

static struct bspforge_clock_data bspforge_clock_data = {{
    .cpu_on = true,
    .timer_on = false,
}};
DEVICE_DEFINE(bspforge_clock, BSPFORGE_CLOCK_NAME, NULL, NULL,
              &bspforge_clock_data, NULL, POST_KERNEL, 70,
              &bspforge_clock_api);

const struct device *bspforge_zephyr_clock_device(void)
{{
    return DEVICE_GET(bspforge_clock);
}}

struct bspforge_uart_data {{
    struct uart_config config;
}};

static int bspforge_uart_init_api(const struct device *dev)
{{
    struct bspforge_uart_data *data = dev->data;
    int result = bspforge_uart_initialize();

    if (result != 0)
        return result;
    data->config = (struct uart_config){{
        .baudrate = 115200U,
        .parity = UART_CFG_PARITY_NONE,
        .stop_bits = UART_CFG_STOP_BITS_1,
        .data_bits = UART_CFG_DATA_BITS_8,
        .flow_ctrl = UART_CFG_FLOW_CTRL_NONE,
    }};
    return 0;
}}

static int bspforge_uart_poll_in_api(const struct device *dev,
                                     unsigned char *value)
{{
    ARG_UNUSED(dev);
    return bspforge_uart_read(value, 1U) == 1 ? 0 : -1;
}}

static void bspforge_uart_poll_out_api(const struct device *dev,
                                       unsigned char value)
{{
    ARG_UNUSED(dev);
    (void)bspforge_uart_write(&value, 1U);
}}

static int bspforge_uart_err_check_api(const struct device *dev)
{{
    ARG_UNUSED(dev);
    return 0;
}}

static int bspforge_uart_configure_api(const struct device *dev,
                                       const struct uart_config *config)
{{
    struct bspforge_uart_data *data = dev->data;

    if (config == NULL || config->baudrate == 0U ||
        config->parity != UART_CFG_PARITY_NONE ||
        config->stop_bits != UART_CFG_STOP_BITS_1 ||
        config->data_bits != UART_CFG_DATA_BITS_8 ||
        config->flow_ctrl != UART_CFG_FLOW_CTRL_NONE)
        return -ENOTSUP;
    if (bspforge_uart_configure(config->baudrate) != 0)
        return -EIO;
    data->config = *config;
    return 0;
}}

static int bspforge_uart_config_get_api(const struct device *dev,
                                        struct uart_config *config)
{{
    struct bspforge_uart_data *data = dev->data;

    if (config == NULL)
        return -EINVAL;
    *config = data->config;
    return 0;
}}

static struct bspforge_uart_data bspforge_uart_data;
static DEVICE_API(uart, bspforge_uart_api) = {{
    .poll_in = bspforge_uart_poll_in_api,
    .poll_out = bspforge_uart_poll_out_api,
    .err_check = bspforge_uart_err_check_api,
    .configure = bspforge_uart_configure_api,
    .config_get = bspforge_uart_config_get_api,
}};

DEVICE_DEFINE(bspforge_uart, BSPFORGE_UART_NAME, bspforge_uart_init_api, NULL,
              &bspforge_uart_data, NULL, POST_KERNEL, 80, &bspforge_uart_api);

const struct device *bspforge_zephyr_uart_device(void)
{{
    return DEVICE_GET(bspforge_uart);
}}

struct bspforge_gpio_config {{
    struct gpio_driver_config common;
}};

struct bspforge_gpio_data {{
    struct gpio_driver_data common;
    sys_slist_t callbacks;
    const struct device *device;
}};

static int bspforge_gpio_sdk_callback(void *context)
{{
    struct bspforge_gpio_data *data = context;

    gpio_fire_callbacks(&data->callbacks, data->device,
                        BIT(BSPFORGE_GPIO_INPUT_PIN));
    return 0;
}}

static int bspforge_gpio_init_api(const struct device *dev)
{{
    struct bspforge_gpio_data *data = dev->data;

    data->device = dev;
    sys_slist_init(&data->callbacks);
    return bspforge_gpio_initialize();
}}

static int bspforge_gpio_pin_configure_api(const struct device *dev,
                                           gpio_pin_t pin,
                                           gpio_flags_t flags)
{{
    ARG_UNUSED(dev);
    if (pin == BSPFORGE_GPIO_OUTPUT_PIN && (flags & GPIO_OUTPUT)) {{
        if (flags & GPIO_OUTPUT_INIT_HIGH)
            return bspforge_gpio_write(1U);
        if (flags & GPIO_OUTPUT_INIT_LOW)
            return bspforge_gpio_write(0U);
        return 0;
    }}
    if (pin == BSPFORGE_GPIO_INPUT_PIN && (flags & GPIO_INPUT))
        return 0;
    return -ENOTSUP;
}}

static int bspforge_gpio_port_get_api(const struct device *dev,
                                      gpio_port_value_t *value)
{{
    int input;
    int output;

    ARG_UNUSED(dev);
    if (value == NULL)
        return -EINVAL;
    input = bspforge_gpio_read();
    output = bspforge_gpio_output_latch();
    if (input < 0 || output < 0)
        return -EIO;
    *value = (input ? BIT(BSPFORGE_GPIO_INPUT_PIN) : 0U) |
             (output ? BIT(BSPFORGE_GPIO_OUTPUT_PIN) : 0U);
    return 0;
}}

static int bspforge_gpio_port_set_masked_api(const struct device *dev,
                                             gpio_port_pins_t mask,
                                             gpio_port_value_t value)
{{
    ARG_UNUSED(dev);
    if ((mask & BIT(BSPFORGE_GPIO_OUTPUT_PIN)) == 0U)
        return 0;
    return bspforge_gpio_write(
        (value & BIT(BSPFORGE_GPIO_OUTPUT_PIN)) != 0U ? 1U : 0U);
}}

static int bspforge_gpio_port_set_bits_api(const struct device *dev,
                                           gpio_port_pins_t pins)
{{
    return bspforge_gpio_port_set_masked_api(dev, pins, pins);
}}

static int bspforge_gpio_port_clear_bits_api(const struct device *dev,
                                             gpio_port_pins_t pins)
{{
    return bspforge_gpio_port_set_masked_api(dev, pins, 0U);
}}

static int bspforge_gpio_port_toggle_bits_api(const struct device *dev,
                                              gpio_port_pins_t pins)
{{
    int output;

    ARG_UNUSED(dev);
    if ((pins & BIT(BSPFORGE_GPIO_OUTPUT_PIN)) == 0U)
        return 0;
    output = bspforge_gpio_output_latch();
    return output < 0 ? -EIO : bspforge_gpio_write(output == 0 ? 1U : 0U);
}}

static int bspforge_gpio_interrupt_configure_api(
    const struct device *dev, gpio_pin_t pin,
    enum gpio_int_mode mode, enum gpio_int_trig trigger)
{{
    struct bspforge_gpio_data *data = dev->data;

    if (pin != BSPFORGE_GPIO_INPUT_PIN)
        return -ENOTSUP;
    if (mode == GPIO_INT_MODE_DISABLED) {{
        bspforge_gpio_irq_unregister();
        return 0;
    }}
    if (mode != GPIO_INT_MODE_EDGE || trigger != GPIO_INT_TRIG_HIGH)
        return -ENOTSUP;
    return bspforge_gpio_irq_register(bspforge_gpio_sdk_callback, data);
}}

static int bspforge_gpio_manage_callback_api(const struct device *dev,
                                              struct gpio_callback *callback,
                                              bool set)
{{
    struct bspforge_gpio_data *data = dev->data;

    return gpio_manage_callback(&data->callbacks, callback, set);
}}

static const struct bspforge_gpio_config bspforge_gpio_config = {{
    .common = {{
        .port_pin_mask = BIT(BSPFORGE_GPIO_OUTPUT_PIN) |
                         BIT(BSPFORGE_GPIO_INPUT_PIN),
    }},
}};
static struct bspforge_gpio_data bspforge_gpio_data;
static DEVICE_API(gpio, bspforge_gpio_api) = {{
    .pin_configure = bspforge_gpio_pin_configure_api,
    .port_get_raw = bspforge_gpio_port_get_api,
    .port_set_masked_raw = bspforge_gpio_port_set_masked_api,
    .port_set_bits_raw = bspforge_gpio_port_set_bits_api,
    .port_clear_bits_raw = bspforge_gpio_port_clear_bits_api,
    .port_toggle_bits = bspforge_gpio_port_toggle_bits_api,
    .pin_interrupt_configure = bspforge_gpio_interrupt_configure_api,
    .manage_callback = bspforge_gpio_manage_callback_api,
}};

DEVICE_DEFINE(bspforge_gpio, BSPFORGE_GPIO_NAME, bspforge_gpio_init_api, NULL,
              &bspforge_gpio_data, &bspforge_gpio_config, POST_KERNEL, 80,
              &bspforge_gpio_api);

const struct device *bspforge_zephyr_gpio_device(void)
{{
    return DEVICE_GET(bspforge_gpio);
}}

const struct device *bspforge_zephyr_gpio_input_device(void)
{{
    return DEVICE_GET(bspforge_gpio);
}}

enum bspforge_counter_mode {{
    BSPFORGE_COUNTER_IDLE,
    BSPFORGE_COUNTER_ALARM,
    BSPFORGE_COUNTER_PERIODIC,
}};

struct bspforge_counter_data {{
    const struct device *device;
    enum bspforge_counter_mode mode;
    bool started;
    uint32_t ticks;
    struct counter_alarm_cfg alarm;
    struct counter_top_cfg top;
}};

static int bspforge_counter_sdk_callback(void *context)
{{
    struct bspforge_counter_data *data = context;

    if (data->mode == BSPFORGE_COUNTER_ALARM && data->alarm.callback != NULL) {{
        counter_alarm_callback_t callback = data->alarm.callback;
        void *user_data = data->alarm.user_data;

        data->mode = BSPFORGE_COUNTER_IDLE;
        callback(data->device, 0U, bspforge_timer_count(), user_data);
    }} else if (data->mode == BSPFORGE_COUNTER_PERIODIC &&
               data->top.callback != NULL) {{
        data->top.callback(data->device, data->top.user_data);
    }}
    return 0;
}}

static int bspforge_counter_arm(struct bspforge_counter_data *data)
{{
    if (data->mode == BSPFORGE_COUNTER_IDLE || data->ticks == 0U)
        return 0;
    return bspforge_timer_start(
        data->ticks,
        data->mode == BSPFORGE_COUNTER_ALARM,
        bspforge_counter_sdk_callback,
        data);
}}

static int bspforge_counter_init_api(const struct device *dev)
{{
    struct bspforge_counter_data *data = dev->data;

    data->device = dev;
    data->mode = BSPFORGE_COUNTER_IDLE;
    return bspforge_timer_initialize();
}}

static int bspforge_counter_start_api(const struct device *dev)
{{
    struct bspforge_counter_data *data = dev->data;

    data->started = true;
    return bspforge_counter_arm(data);
}}

static int bspforge_counter_stop_api(const struct device *dev)
{{
    struct bspforge_counter_data *data = dev->data;

    data->started = false;
    data->mode = BSPFORGE_COUNTER_IDLE;
    return bspforge_timer_stop();
}}

static int bspforge_counter_get_value_api(const struct device *dev,
                                          uint32_t *ticks)
{{
    ARG_UNUSED(dev);
    if (ticks == NULL)
        return -EINVAL;
    *ticks = bspforge_timer_count();
    return 0;
}}

static int bspforge_counter_set_alarm_api(
    const struct device *dev, uint8_t channel,
    const struct counter_alarm_cfg *config)
{{
    struct bspforge_counter_data *data = dev->data;

    if (channel != 0U || config == NULL || config->callback == NULL ||
        config->ticks == 0U || (config->flags & COUNTER_ALARM_CFG_ABSOLUTE))
        return -EINVAL;
    data->mode = BSPFORGE_COUNTER_ALARM;
    data->ticks = config->ticks;
    data->alarm = *config;
    return data->started ? bspforge_counter_arm(data) : 0;
}}

static int bspforge_counter_cancel_alarm_api(const struct device *dev,
                                              uint8_t channel)
{{
    struct bspforge_counter_data *data = dev->data;

    if (channel != 0U)
        return -EINVAL;
    data->mode = BSPFORGE_COUNTER_IDLE;
    memset(&data->alarm, 0, sizeof(data->alarm));
    return bspforge_timer_stop();
}}

static int bspforge_counter_set_top_api(const struct device *dev,
                                        const struct counter_top_cfg *config)
{{
    struct bspforge_counter_data *data = dev->data;

    if (config == NULL || config->callback == NULL || config->ticks == 0U)
        return -EINVAL;
    data->mode = BSPFORGE_COUNTER_PERIODIC;
    data->ticks = config->ticks;
    data->top = *config;
    return data->started ? bspforge_counter_arm(data) : 0;
}}

static uint32_t bspforge_counter_get_pending_api(const struct device *dev)
{{
    ARG_UNUSED(dev);
    return 0U;
}}

static uint32_t bspforge_counter_get_top_api(const struct device *dev)
{{
    const struct bspforge_counter_data *data = dev->data;

    return data->ticks == 0U ? UINT32_MAX : data->ticks;
}}

static uint32_t bspforge_counter_get_frequency_api(const struct device *dev)
{{
    ARG_UNUSED(dev);
    return 1000000000U;
}}

static const struct counter_config_info bspforge_counter_config = {{
    .freq = 1000000000U,
    .max_top_value = UINT32_MAX,
    .flags = COUNTER_CONFIG_INFO_COUNT_UP,
    .channels = 1U,
}};
static struct bspforge_counter_data bspforge_counter_data;
static DEVICE_API(counter, bspforge_counter_api) = {{
    .start = bspforge_counter_start_api,
    .stop = bspforge_counter_stop_api,
    .get_value = bspforge_counter_get_value_api,
    .set_alarm = bspforge_counter_set_alarm_api,
    .cancel_alarm = bspforge_counter_cancel_alarm_api,
    .set_top_value = bspforge_counter_set_top_api,
    .get_pending_int = bspforge_counter_get_pending_api,
    .get_top_value = bspforge_counter_get_top_api,
    .get_freq = bspforge_counter_get_frequency_api,
}};

DEVICE_DEFINE(bspforge_counter, BSPFORGE_COUNTER_NAME,
              bspforge_counter_init_api, NULL, &bspforge_counter_data,
              &bspforge_counter_config, POST_KERNEL, 80,
              &bspforge_counter_api);

const struct device *bspforge_zephyr_counter_device(void)
{{
    return DEVICE_GET(bspforge_counter);
}}
'''
